---
collections:
  - name: cloud.terraform
    version: 1.0.0
  - name: amazon.aws
    version: 3.1.1
  - name: redhat.rhel_system_roles
  - name: ansible.posix
  - name: redhat.rhel_system_roles
    version: 1.21.1
  - name: carlos_zrm.teams_msg
    version: 1.0.0